name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - main
env:
  # Global environment variable
  IMAGE: qgis/qgis
  WITH_PYTHON_PEP: "true"
  MUTE_LOGS: "false"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Running tests on ${{ matrix.os }} using QGIS ${{ matrix.qgis_version_tag }}

    strategy:
      fail-fast: false
      matrix:
        qgis_version_tag:
          - release-3_30
          - release-3_32
          - release-3_34
          - release-3_36
          #- release-3_38
          #- release-3_40
        os: [ubuntu-22.04]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Preparing docker-compose environment
        env:
          QGIS_VERSION_TAG: ${{ matrix.qgis_version_tag }}
          ORS_API_KEY: ${{ secrets.ORS_API_KEY }}
        run: |
          cat << EOF > .env
          QGIS_VERSION_TAG=${QGIS_VERSION_TAG}
          IMAGE=${IMAGE}
          ON_TRAVIS=true
          MUTE_LOGS=${MUTE_LOGS}
          WITH_PYTHON_PEP=${WITH_PYTHON_PEP}
          ORS_API_KEY=${ORS_API_KEY}
          EOF
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install plugin dependencies
        run: pip install -r requirements-dev.txt

      - name: Preparing test environment
        run: |
          docker pull "${IMAGE}":${{ matrix.qgis_version_tag }}
          python admin.py build --tests
          docker compose up -d
          sleep 10

      - name: Run test suite
        run: |
          docker compose exec -T qgis-testing-environment qgis_testrunner.sh test_suite.test_package